apiVersion: v1
kind: Service
metadata:
  name: moderation-service
spec:
  type: NodePort
  selector:
    app: moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 4002
      targetPort: 4002
